name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python requirements
        run: pip install -r requirements/lint_format.txt
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: firstaid
          args: format --check
      - uses: chartboost/ruff-action@v1
        with:
          src: firstaid
          args: check
